### ISSUE TITLE
Shorthand for saturation function?

### ISSUE THREAD

**Issue by xjtu-blacksmith** [thermalogic/SEUIF97#6]
Usually steam property lib may offer **saturation functions**, e.g. computing enthalpy of saturated water/steam. It is possible to pack such functions through current interfaces offered by SEUIF97 though, in Python for example:

```python
import seuif97
pV2h = lambda p: seuif97.px2h(p, 1)  # compute enthalpy of saturated steam by pressure
pL2h = lambda p: seuif97.px2h(p, 0)  # compute enthalpy of saturated water by pressure
```

But it might be more convenient to have such interfaces in SEUIF97 itself ...

**Comment by thermalogic** [comment]
You can calculate steam properties in the interfaces that are convenient for you.

**Comment by xjtu-blacksmith** [comment]
Fine. Thanks for your creative works!
